linters:
  enable-all: true
  disable:
    - cyclop
    - deadcode
    - errname
    - exhaustive
    - exhaustruct
    - exhaustivestruct
    - forbidigo
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - godot
    - godox
    - golint
    - gofumpt
    - gomnd
    - ifshort
    - interfacer
    - lll
    - maligned
    - nestif
    - nilnil
    - nlreturn
    - nosnakecase
    - paralleltest
    - scopelint
    - structcheck
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - varcheck
    - varnamelen
    - wrapcheck
    - wsl

linters-settings:
  importas:
    # Do not allow unaliased imports of aliased packages.
    # Default: false
    no-unaliased: true
    alias:
      # Kubernetes
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
        alias: apiextensionsv1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: apierrors
      - pkg: k8s.io/apimachinery/pkg/util/errors
        alias: kerrors
      # Controller Runtime
      - pkg: sigs.k8s.io/controller-runtime
        alias: ctrl
  tagliatelle:
    case:
      rules:
        # Any struct tag type can be used.
        # Support string case: `camel`, `pascal`, `kebab`, `snake`, `goCamel`, `goPascal`, `goKebab`, `goSnake`, `upper`, `lower`, `header`
        json: goCamel
  gomoddirectives:
    # List of allowed `replace` directives.
    # Default: []
    replace-allow-list:
      - sigs.k8s.io/cluster-api
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: sigs.k8s.io/cluster-api-provider-packet
  nolintlint:
    # Enable to require nolint directives to mention the specific linter being suppressed.
    # Default: false
    require-specific: true
  revive:
    rules:
      - name: unused-parameter
        disabled: true

run:
  go: '1.19'
  timeout: 10m
  skip-files:
  - "zz_generated.*\\.go$"
  - ".*conversion.*\\.go$"
  allow-parallel-runners: true
